In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = "1"

#Library

In [ ]:
pip install transformers==4.3.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers==4.3.0
  Downloading transformers-4.3.0-py3-none-any.whl (1.8 MB)
     |████████████████████████████████| 1.8 MB 32.8 MB/s
Collecting sacremoses
  Downloading sacremoses-0.0.53.tar.gz (880 kB)
     |████████████████████████████████| 880 kB 14.7 MB/s
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (2019.12.20)
Requirement already satisfied: packaging in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (21.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (4.64.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (1.21.6)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (4.11.4)
Requirement already satisfied: filelock in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (3.7.0)
Collecting tokenizers<0.11,>=0.10.1
  Downloading tokenizers-0.10.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (3.3 MB)
     |████████████████████████████████| 3.3 MB 53.1 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from transformers==4.3.0) (2.23.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers==4.3.0) (4.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->transformers==4.3.0) (3.8.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging->transformers==4.3.0) (3.0.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==4.3.0) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==4.3.0) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==4.3.0) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->transformers==4.3.0) (2022.5.18.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers==4.3.0) (1.15.0)
Requirement already satisfied: click in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers==4.3.0) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.7/dist-packages (from sacremoses->transformers==4.3.0) (1.1.0)
Building wheels for collected packages: sacremoses
  Building wheel for sacremoses (setup.py) ... done
  Created wheel for sacremoses: filename=sacremoses-0.0.53-py3-none-any.whl size=895260 sha256=ebcaff9ee47e6b3634971e1ebe1d8054f4d1e56549ef7cf22a308e59d335821d
  Stored in directory: /root/.cache/pip/wheels/87/39/dd/a83eeef36d0bf98e7a4d1933a4ad2d660295a40613079bafc9
Successfully built sacremoses
Installing collected packages: tokenizers, sacremoses, transformers
Successfully installed sacremoses-0.0.53 tokenizers-0.10.3 transformers-4.3.0

In [ ]:
pip install vncorenlp

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting vncorenlp
  Downloading vncorenlp-1.0.3.tar.gz (2.6 MB)
     |████████████████████████████████| 2.6 MB 28.4 MB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from vncorenlp) (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->vncorenlp) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->vncorenlp) (2022.5.18.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->vncorenlp) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->vncorenlp) (2.10)
Building wheels for collected packages: vncorenlp
  Building wheel for vncorenlp (setup.py) ... done
  Created wheel for vncorenlp: filename=vncorenlp-1.0.3-py3-none-any.whl size=2645951 sha256=aa7d1257ea3228a45a33545a3282c7d538bdbf785ae43fbba2d207c485315eb8
  Stored in directory: /root/.cache/pip/wheels/0c/d8/f2/d28d97379b4f6479bf51247c8dfd57fa00932fa7a74b6aab29
Successfully built vncorenlp
Installing collected packages: vncorenlp
Successfully installed vncorenlp-1.0.3

In [ ]:
!mkdir -p vncorenlp/models/wordsegmenter
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/vi-vocab
!wget https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/wordsegmenter.rdr
!mv VnCoreNLP-1.1.1.jar vncorenlp/
!mv vi-vocab vncorenlp/models/wordsegmenter/
!mv wordsegmenter.rdr vncorenlp/models/wordsegmenter/

--2022-06-11 12:54:17--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/VnCoreNLP-1.1.1.jar
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 27412575 (26M) [application/octet-stream]
Saving to: ‘VnCoreNLP-1.1.1.jar’

VnCoreNLP-1.1.1.jar 100%[===================>]  26.14M  --.-KB/s    in 0.1s

2022-06-11 12:54:20 (193 MB/s) - ‘VnCoreNLP-1.1.1.jar’ saved [27412575/27412575]

--2022-06-11 12:54:20--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/vi-vocab
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 526544 (514K) [application/octet-stream]
Saving to: ‘vi-vocab’

vi-vocab            100%[===================>] 514.20K  --.-KB/s    in 0.003s

2022-06-11 12:54:21 (145 MB/s) - ‘vi-vocab’ saved [526544/526544]

--2022-06-11 12:54:21--  https://raw.githubusercontent.com/vncorenlp/VnCoreNLP/master/models/wordsegmenter/wordsegmenter.rdr
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 128508 (125K) [text/plain]
Saving to: ‘wordsegmenter.rdr’

wordsegmenter.rdr   100%[===================>] 125.50K  --.-KB/s    in 0.003s

2022-06-11 12:54:21 (48.1 MB/s) - ‘wordsegmenter.rdr’ saved [128508/128508]

#Data loader and preprocessing

In [ ]:
#load dataset crawl được từ youtube
import pandas as pd

test = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/data4.csv", index_col=False)
test.reset_index(drop=True)
test['Pseudo Label'] = 0
test

                                               Comment  Likes  Pseudo Label
0    STREET DANCE VIỆT NAM - TẬP 3 full video https...      2             0
1    Mỗi một giây của chương trình đều làm mình nổi...     73             0
2    Phải đến đoạn Trọng Hiếu nhảy mới dám mở to 2 ...     76             0
3      Nhìn Trọng Hiếu nhảy mà tui muốn nhảy theo luôn     13             0
4    Bật lại mấy cái clip hip hop ngày xưa , giờ co...     14             0
5    Chời ơi đỡ tui :)))))) cừi chết với cú ke đầu ...     45             0
6    Với khả năng nhảy, đặc biệt là quả ke đầu này,...     76             0
7    Nhìn mặt bà pu hài vl 🤣🤣🤣🤣 t coi trên fb nói v...     13             0
8    Show rất hay, ngoài làm thí sinh thì họ cũng l...     19             0
9    Một gameshow về dance mà bốn đội trưởng chỉ mỗ...     78             0
10   Trọng hiếu nhảy quá đỉnh và thần thái quan trọ...      0             0
11   10:51 mình expect cái "ke đầu" mn nói tới sẽ r...     24             0
12   Cười vl =)))) Toàn pha xịt nhưng reaction hú h...     16             0
13   Nếu Bảo Anh nhảy như thế mà đc làm đội trưởng....      9             0
14   Ko biết bọn dancer nước ngoài xem dc trương tr...      2             0
15   Trọng Hiếu gánh cả chương trình 😢 đẳng cấp khá...      0             0
16   ChiPu ráng làm như The RF =]]. Cứ mỗi lần thấy...      2             0
17   10:50 Chipu ke đầu nha mn 😌😌😌 Thiệt xem mà khô...     28             0
18                   Tran Thành nhảy cười vãi chưởng 🤣      0             0
19   Chipu chỉ nên nhảy k nên hát còn bảo anh thì n...      0             0
20   Nhìn trọng hiếu nhảy là biết chuyên nghiệp và ...      3             0
21               Trọng Hiếu gánh chương trình liệt giò     23             0
22   Cảm thấy tội nghiệp Trọng Hiếu vl, cân mẹ cái ...     23             0
23                             Vừa Cháy Vừa Chiến 🔥🔥🤘🤘      1             0
24   Có 1 số người ăn ì mà vô duyên hết sức lúc nào...      1             0
25   Cám ơn bạn Chi Pu cho mình trở về với tuổi thơ...     15             0
26   Chi Pu quá xuất sắc đâu  phải ai cung  có năng...      0             0
27   Chipu có lẽ nên chuyển dần sang mảng diễn viên...      2             0
28   Tao hy vọng nước ngoài họ ko xem đc chương trì...      0             0
29   Chiến lên a Hiếu ơi!E luôn theo dõi anh!!Chiến...      2             0
30    Trấn Thành đúng là MC quốc dân luôn. Đỉnh chóp 👏      1             0
31   Mình nghĩ cái cypher này nó chỉ cháy nếu bạn t...     13             0
32    Ctrinh có Trấn Thành là hiểu phải có tấu hài rồi      0             0
33   Thứ tự hạng theo mình: Trọng Hiếu > Kay Trần >...      1             0
34   Khắt khe làm gì, mình thấy 4 đội trưởng đang c...     13             0
35                                   Kay đẹp troai vãi      1             0
36                 Chi poo ke đầu mắc cừi vcl🤡🤡🤡🔥🔥👍👍✨✨      7             0
37              Chipu nay có quả quần lọt khe đỉnh vãi      0             0
38   Có đc mỗi Trọng Hiếu nhìn ok, còn lại toàn loă...      2             0
39   Xem 5 lần vẫn thấy hay. K bit ji về nhảy. Nhưn...      1             0
40   Tao cá là quả ke đầu yoga của CP các giám khảo...      0             0
41   Dù có công nhận hay ko thì   chipu nhảy đỉnh t...      5             0
42                             Nhìn Chi pu bùn cừi 😂😂😂      2             0
43                   Trấn Thành nhảy gia gì phết nhỉ 😁      2             0
44                          Nhìn bảo anh nhảy kìa 🤣🤣🤣🤣      0             0
45   không hiểu sao mà lại nhiều người xung quanh l...      1             0
46   Mỗi người 200k hộp cơm với chai nước. Xin cảm ...      7             0
47   Bảo Anh nhảy chán quá ko xem đc miếng nào luôn...     20             0
48   Sao thấy mọi người khắt khe quá nhỉ. Dù là nhả...      6             0
49   Thật sự éo hiểu tại sao mọi người hú hét quả k...      1             0
50   Thiếu gì người biết nhảy ko mời. Đi mời kay tr...      1             0
51   Ngoại trừ Trọng Hiếu  thì không biết là huấn l...      0             0
52             Trọng hiếu và phần còn lại của ctrinh 🤣      0             0
53   tấu hài vc, Chipu toàn mấy pha xịt thôi rồi mà...      2             0
54                                             Quá đẹp      0             0
55   Minh nghi sao moi ng lai khắc khe. Tinh thần c...      1             0
56       ngoài trọng hiếu ra thì còn lại y như múa lân      2             0
57   2:23 bà Chipu bả hô tên thôi mà cũng crack nữa...      2             0
58   Đoạn đầu Chi pu bày đặt đá chân ngay chỗ trọng...      1             0
59                                         Tấu hài vcl      0             0
60   Có ai để ý mỗi lần chi pu và bảo anh nhảy là c...      3             0
61                      BA kiểu nhảy nhẹ nhàng quá nhỉ      1             0
62                       Côg nhận chi pu nhảy điêu nhe      0             0
63                                    chi pu chất thật      1             0
64          Chipu nhảy ok mà mn, trừ quả ke đầu j đó 🤣      0             0
65   Ai đã coi street dance china 4 mùa như tui chắ...      1             0
66                   Thấy Bảo Anh chắc tếu nhất á :)))      2             0
67   tò mò cái ke đầu qua tua mãi ms thấy, đúng tấu...      4             0
68   Hong chị nhảy cũng đẹp nhưng la thôi đã lạc gi...      0             0
69                                      nhảy đẹp lắm ạ      0             0
70   Ko hát rồi mà tự hét tên mình thôi vẫn oét đc ...      1             0
71   =))))) chị Chee poo ngoáy ngoáy zì zạ trông mắ...      1             0
72                                Bảo Anh nhảy hề vãi.      0             0
73   Ra lắc eo qua lại nhún mấy cái ra street dance=))      0             0
74   con mặt dày TreePoo càng ngày càng thể hiện rõ...      1             0
75   Hay lắm Chi Pu, quả ke đầu nhìn tín đấy, còn B...      0             0
76   Chipu tấu hài à. Ngta tập yoga lộn còn đẹp hơn...      1             0
77    có thế mà cũng gọi là "cú ke đầu lịch sử" cười ẻ      0             0
78   chương trình mang tên Trọng Hiếu và 4 chú hề =)))      1             0
79   Cứ tưởng ke đầu ntn? Xem cười vỡ bụng, tự nhiê...      1             0
80                                           Tuyệt ghê      0             0
81                                         Chị Pu đỉnh      1             0
82                                Thiik mỗi trọng hiếu      0             0
83             Trong Hiếu vẫn là 1 cái gì đó out trình      5             0
84     battle gì mà lắc mông không vậy ạ :')))) sợ quá      0             0
85                              Như xem hài Chi Pu :))      1             0
86   Trong hieu la chuyen nghiem roi ko con gi phai...      0             0
87   bảo ảnh vào làm trò hề àchưa có cái tuổi trong...      0             0
88                                          DANCE GOOG      0             0
89   Chi Pu ke đầu nửa vời thì khen lấy khen để. Rồ...      1             0
90   Kay trần nhảy oke mà mn ơi so vs dân nhảy cx l...     20             0
91   Con đuông dừa bảo anh và con loăng quăng thị c...      1             0
92                             Nhìn em bảo anh nhảy vl      0             0
93           Ke đầu lịch sử=)))) Trò cười thì đúng hơn      1             0
94               Nhớ cái hồi bước nhảy xì ten ghê  :))      0             0
95          10p50s cho ai tìm Chipu bẻ cái đầu nhaaaaa      0             0
96                                    Bảo Anh nhảy🤣🤣🤣🤣      1             0
97   Nuoc nào cũng vậy thoi đội  trưởng tất nhiên p...      0             0
98   Ke đâu ke đâu ke đâu ke đâu 🙄🙄, thấy bóng dáng...      0             0
99   Thà để chi pâu nó nhẩy đi. Đừng để nó cất giọn...      2             0
100                          Bảo Anh hơi đuối nhở :)))      1             0
101   Thấy cùi cùi kiểu gì ấy, bên china nhảy đỉnh hơn      0             0
102  Bảo Anh nhảy chán v~, ra uốn éo vài cái rồi th...      0             0
103        Nhảy không giỏi mà biểu cảm nó ố dề thật sự      1             0
104  Mọi người thử search: "Hội những người thất tì...      0             0
105              nhẩy bòi gì cứ như loăng quăng kk      0             0
106  Trừ trọng hiếu ra, còn lại thấy nhảy như thời ...      5             0
107           Treepoo cố hét hay nói to nghe diva vlll      1             0
108  Nó như kiểu hàng fake của phiên bản Trung Quốc...      0             0
109  Pha cầm giày của Kay giống của Nhất Bác quá vậ...      2             0
110  Tao thề là bà bảo anh làm gì trong truong trìn...      2             0
111             Vào đây để xem quả ke đầu yoga. Duyệt!      0             0
112                         như đười ươi đu cột điện 💀      0             0
113  Chipu tấu hài còn cứ hơn bảo anh 1 màu quoá, b...      4             0
114         T mới đọc báo nên vô coi chi pu ke đầu kkk      1             0
115           Này gọi là ke à đầu à :)) nhám nhí thiệt      1             0
116                            xem chọi gà còn vui hơn      0             0
117  Cho hỏi bà bảo anh nhảy chưa vậy 😑😑.ra nhúng n...      2             0
118                       8:03 là bài gì vậy mọi người      0             0
119                   nhảy nhót nhìn chán k chịu được!      0             0
120                         = ))))))))))))))))))))))))      0             0
121                  Không bằng mấy e cấp 3 dàn dựng 😂      2             0
122       Khán giả đc trả bao tiền cho quả ke đầu này?      0             0
123          má, gì mà như rạp xiếc tấu hài vậy tr :((      0             0
124  Tôi đang xem cái gì đây :)))) cười k nhặt được...      0             0
125            Haiz vãi:)) cơ mà Trthanh dct rất duyên      0             0
126                  xem china xong xem vnam chan cmnl      0             0
127                    Ban giám khảo còn thua cả dance      0             0
128  Ô sao có logo giống báo đen của Vương Nhất Bác...      0             0
129                Pu giờ có vòng eo ngon đấy nhựttt..      1             0
130           ukm ke đầu lịch sử.. @_@ lịch sử tấu hài      1             0
131                                   buồn cười vcl :)     12             0
132                      thách thức danh hài à ace :))      0             0
133     tôi thấy nó cứ cùi cùi kiểu gì ấy, cả cái show      0             0
134                            7:03 :> túy quyền đây ư      0             0
135                     bảo anh làm cái trò mèo gì vậy      0             0
136           pu oj nho qua thom mjeng nha me may hjjj      0             0
137     Con Chi Pu nó làm cái gì vạy, nhìn ngứa cả mắt      1             0
138              Một dislike dành cho CHI PU & BẢO ANH      0             0
139          Đó gọi là ke hả hay búng lên cái r rớt???      0             0
140                              Phút 10:49 cho ai cần      0             0
141  Chương trình thế giới động vật nay mở nhạc to thế      0             0
142                                             CHÊ :)      0             0
143                          Bảo Anh nhảy gì vậy? Gớm😅      7             0
144                                             hahaha      0             0
145  Kay Trần nhảy cái điệu nhảy cầm giày thấy nó q...      0             0
146                        Ủa rồi Bảo Anh nhảy chưa? 🤣      0             0
147                    Trấn Thành có cái áo xấu vãiiii      0             0
148                     Nhảy cóc nhảy nhái zì vậy?????      0             0
149                                10:51 react lố vchg      0             0
150    Éo hiểu con pu nhảy có gì hay mà la hết thế nhỉ      1             0
151                         Con nít cũng làm dc cái đó      0             0
152                  Đ khác j mấy con loăng quoăng :))      1             0
153                            đùa = ))))))) bcuoi vcd      0             0
154  má ơi thấy bả đăng cái gì ke đầu đỉnh dữ lắm g...      3             0
155  Thôi cho bà chipu và bà bảo anh về đi hát đi.c...      1             0
156                      Xếp theo level thìHiếuKayPuBA      7             0
157                                             Cười ẻ      0             0
158      Hôm nay xem youtube thế này là đủ r, ngại quá      0             0
159                                 Game show rác :)))      0             0
160                                 CRINGE VAIZ CẢ LOZ      0             0
161                                      Nhảy thấy gớm      0             0
162                            Clm nói không cũng oét…      0             0
163  Chi nhảy cx đẹp mà mnMn đánh giá công tâm chút...      1             0
164  Con kênh 13+1 kêu CP ke đầu đi vào lsu ct làm ...      0             0
165                    Chương trình tấu hài. Nhảm vccc      0             0
166                              Hẳn ke đầu 2 giây 🤣🤣🤣      9             0
167                                     buồn cuoiyvqix      1             0
168                   Mấy ng này đng làm cái gì dẫy???      3             0
169                                    kiểu bu vô xu!?      0             0
170                                  BA nhảy clg v huh      0             0
171                         Tôi đang xem cái gì v:))??      7             0
172                      Rạp xiếc trung ương xuất hiện      0             0
173                                Rạp xiếc trung ương      0             0
174                                                ???      0             0
175                                  Tao đang coi clgv      0             0
176      t chỉ muốn biết là t đang xem cl gì thế này??      0             0
177                       Clmn làm vô coi ke đầu !!!!!      2             0

In [ ]:
from vncorenlp import VnCoreNLP

vncorenlp = VnCoreNLP("vncorenlp/VnCoreNLP-1.1.1.jar", annotators="wseg", max_heap_size='-Xmx500m')

In [ ]:
#pre-process
import re
import numpy as np

STOPWORDS = '/content/drive/MyDrive/Colab Notebooks/ViHSD/vietnamese-stopwords.txt'
with open(STOPWORDS, "r") as ins:
    stopwords = []
    for line in ins:
        dd = line.strip('\n')
        stopwords.append(dd)
    stopwords = set(stopwords)

def filter_stop_words(train_sentences, stop_words):
    new_sent = [word for word in train_sentences.split() if word not in stop_words]
    train_sentences = ' '.join(new_sent)

    return train_sentences

def deEmojify(text):
    regrex_pattern = re.compile(pattern = "["
        u"\U0001F600-\U0001F64F"  # emoticons
        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
        u"\U0001F680-\U0001F6FF"  # transport & map symbols
        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           "]+", flags = re.UNICODE)
    return regrex_pattern.sub(r'',text)

def preprocess(text, tokenized=True, lowercased=True):
    # text = ViTokenizer.tokenize(text)
    # text = ' '.join(vncorenlp.tokenize(text)[0])
    text = filter_stop_words(text, stopwords)
    text = deEmojify(text)
    text = text.lower() if lowercased else text
    if tokenized:
        pre_text = ""
        sentences = vncorenlp.tokenize(text)
        for sentence in sentences:
            pre_text += " ".join(sentence)
        text = pre_text
    return text

def pre_process_features(X, y, tokenized=True, lowercased=True):
    X = [preprocess(str(p), tokenized=tokenized, lowercased=lowercased) for p in list(X)]
    for idx, ele in enumerate(X):
        if not ele:
            np.delete(X, idx)
            np.delete(y, idx)
    return X, y

X_test = test['Comment']
y_test = test['Pseudo Label'].values

#Model

In [ ]:
#load model đã được train
from sklearn.metrics import f1_score, confusion_matrix, accuracy_score, recall_score
from transformers import AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, BertTokenizer, BertForSequenceClassification

import seaborn as sn
import pandas as pd
import matplotlib.pyplot as plt

import torch

model = AutoModelForSequenceClassification.from_pretrained("vinai/phobert-base", num_labels = 3)

model.load_state_dict(torch.load('/content/drive/MyDrive/Colab Notebooks/ViHSD/transformer_model/phobert-v3/pytorch_model.bin'))

Downloading:   0%|          | 0.00/557 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/543M [00:00<?, ?B/s]

Some weights of the model checkpoint at vinai/phobert-base were not used when initializing RobertaForSequenceClassification: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.decoder.bias', 'roberta.pooler.dense.weight', 'roberta.pooler.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at vinai/phobert-base and are newly initialized: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
X_test

0      STREET DANCE VIỆT NAM - TẬP 3 full video https...
1      Mỗi một giây của chương trình đều làm mình nổi...
2      Phải đến đoạn Trọng Hiếu nhảy mới dám mở to 2 ...
3        Nhìn Trọng Hiếu nhảy mà tui muốn nhảy theo luôn
4      Bật lại mấy cái clip hip hop ngày xưa , giờ co...
                             ...
173                                  Rạp xiếc trung ương
174                                                  ???
175                                    Tao đang coi clgv
176        t chỉ muốn biết là t đang xem cl gì thế này??
177                         Clmn làm vô coi ke đầu !!!!!
Name: Comment, Length: 178, dtype: object

In [ ]:
test_X, test_y = pre_process_features(X_test, y_test, tokenized=True, lowercased = False)

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("vinai/phobert-base",use_fast=False)

import torch

class BuildDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

test_encodings = tokenizer(test_X, truncation=True, padding=True, max_length=100)
test_dataset = BuildDataset(test_encodings, test_y)

Downloading:   0%|          | 0.00/895k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.14M [00:00<?, ?B/s]

Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained.

In [ ]:
training_args = TrainingArguments(output_dir='/content/drive/MyDrive/Colab Notebooks/ViHSD/transformer_model/phobert-v3/',no_cuda=False)

trainer = Trainer(model=model,args=training_args)

y_pred_classify = trainer.predict(test_dataset)

In [ ]:
y_pred = np.argmax(y_pred_classify.predictions, axis=-1)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0])

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option("max_rows", None)
#Đưa vector dự đoán label vào dataframe
df_predict = pd.DataFrame(y_pred)
df_predict.columns = ['predict']
#Xóa cột likes
test = test.drop(columns=['Likes', 'Pseudo Label'])
#Nối cột predcit vào test
df_test_predict = test.join(df_predict)
df_test_predict

                                               Comment  predict
0    STREET DANCE VIỆT NAM - TẬP 3 full video https...        0
1    Mỗi một giây của chương trình đều làm mình nổi...        0
2    Phải đến đoạn Trọng Hiếu nhảy mới dám mở to 2 ...        0
3      Nhìn Trọng Hiếu nhảy mà tui muốn nhảy theo luôn        0
4    Bật lại mấy cái clip hip hop ngày xưa , giờ co...        0
5    Chời ơi đỡ tui :)))))) cừi chết với cú ke đầu ...        0
6    Với khả năng nhảy, đặc biệt là quả ke đầu này,...        0
7    Nhìn mặt bà pu hài vl 🤣🤣🤣🤣 t coi trên fb nói v...        0
8    Show rất hay, ngoài làm thí sinh thì họ cũng l...        0
9    Một gameshow về dance mà bốn đội trưởng chỉ mỗ...        0
10   Trọng hiếu nhảy quá đỉnh và thần thái quan trọ...        0
11   10:51 mình expect cái "ke đầu" mn nói tới sẽ r...        0
12   Cười vl =)))) Toàn pha xịt nhưng reaction hú h...        0
13   Nếu Bảo Anh nhảy như thế mà đc làm đội trưởng....        0
14   Ko biết bọn dancer nước ngoài xem dc trương tr...        0
15   Trọng Hiếu gánh cả chương trình 😢 đẳng cấp khá...        0
16   ChiPu ráng làm như The RF =]]. Cứ mỗi lần thấy...        2
17   10:50 Chipu ke đầu nha mn 😌😌😌 Thiệt xem mà khô...        0
18                   Tran Thành nhảy cười vãi chưởng 🤣        0
19   Chipu chỉ nên nhảy k nên hát còn bảo anh thì n...        0
20   Nhìn trọng hiếu nhảy là biết chuyên nghiệp và ...        0
21               Trọng Hiếu gánh chương trình liệt giò        0
22   Cảm thấy tội nghiệp Trọng Hiếu vl, cân mẹ cái ...        0
23                             Vừa Cháy Vừa Chiến 🔥🔥🤘🤘        0
24   Có 1 số người ăn ì mà vô duyên hết sức lúc nào...        0
25   Cám ơn bạn Chi Pu cho mình trở về với tuổi thơ...        0
26   Chi Pu quá xuất sắc đâu  phải ai cung  có năng...        0
27   Chipu có lẽ nên chuyển dần sang mảng diễn viên...        0
28   Tao hy vọng nước ngoài họ ko xem đc chương trì...        0
29   Chiến lên a Hiếu ơi!E luôn theo dõi anh!!Chiến...        0
30    Trấn Thành đúng là MC quốc dân luôn. Đỉnh chóp 👏        0
31   Mình nghĩ cái cypher này nó chỉ cháy nếu bạn t...        0
32    Ctrinh có Trấn Thành là hiểu phải có tấu hài rồi        0
33   Thứ tự hạng theo mình: Trọng Hiếu > Kay Trần >...        0
34   Khắt khe làm gì, mình thấy 4 đội trưởng đang c...        0
35                                   Kay đẹp troai vãi        0
36                 Chi poo ke đầu mắc cừi vcl🤡🤡🤡🔥🔥👍👍✨✨        0
37              Chipu nay có quả quần lọt khe đỉnh vãi        0
38   Có đc mỗi Trọng Hiếu nhìn ok, còn lại toàn loă...        0
39   Xem 5 lần vẫn thấy hay. K bit ji về nhảy. Nhưn...        0
40   Tao cá là quả ke đầu yoga của CP các giám khảo...        0
41   Dù có công nhận hay ko thì   chipu nhảy đỉnh t...        0
42                             Nhìn Chi pu bùn cừi 😂😂😂        0
43                   Trấn Thành nhảy gia gì phết nhỉ 😁        0
44                          Nhìn bảo anh nhảy kìa 🤣🤣🤣🤣        0
45   không hiểu sao mà lại nhiều người xung quanh l...        0
46   Mỗi người 200k hộp cơm với chai nước. Xin cảm ...        0
47   Bảo Anh nhảy chán quá ko xem đc miếng nào luôn...        0
48   Sao thấy mọi người khắt khe quá nhỉ. Dù là nhả...        0
49   Thật sự éo hiểu tại sao mọi người hú hét quả k...        2
50   Thiếu gì người biết nhảy ko mời. Đi mời kay tr...        0
51   Ngoại trừ Trọng Hiếu  thì không biết là huấn l...        0
52             Trọng hiếu và phần còn lại của ctrinh 🤣        2
53   tấu hài vc, Chipu toàn mấy pha xịt thôi rồi mà...        0
54                                             Quá đẹp        0
55   Minh nghi sao moi ng lai khắc khe. Tinh thần c...        0
56       ngoài trọng hiếu ra thì còn lại y như múa lân        0
57   2:23 bà Chipu bả hô tên thôi mà cũng crack nữa...        0
58   Đoạn đầu Chi pu bày đặt đá chân ngay chỗ trọng...        0
59                                         Tấu hài vcl        0
60   Có ai để ý mỗi lần chi pu và bảo anh nhảy là c...        0
61                      BA kiểu nhảy nhẹ nhàng quá nhỉ        0
62                       Côg nhận chi pu nhảy điêu nhe        0
63                                    chi pu chất thật        0
64          Chipu nhảy ok mà mn, trừ quả ke đầu j đó 🤣        0
65   Ai đã coi street dance china 4 mùa như tui chắ...        0
66                   Thấy Bảo Anh chắc tếu nhất á :)))        0
67   tò mò cái ke đầu qua tua mãi ms thấy, đúng tấu...        0
68   Hong chị nhảy cũng đẹp nhưng la thôi đã lạc gi...        0
69                                      nhảy đẹp lắm ạ        0
70   Ko hát rồi mà tự hét tên mình thôi vẫn oét đc ...        0
71   =))))) chị Chee poo ngoáy ngoáy zì zạ trông mắ...        0
72                                Bảo Anh nhảy hề vãi.        0
73   Ra lắc eo qua lại nhún mấy cái ra street dance=))        0
74   con mặt dày TreePoo càng ngày càng thể hiện rõ...        0
75   Hay lắm Chi Pu, quả ke đầu nhìn tín đấy, còn B...        0
76   Chipu tấu hài à. Ngta tập yoga lộn còn đẹp hơn...        0
77    có thế mà cũng gọi là "cú ke đầu lịch sử" cười ẻ        0
78   chương trình mang tên Trọng Hiếu và 4 chú hề =)))        0
79   Cứ tưởng ke đầu ntn? Xem cười vỡ bụng, tự nhiê...        1
80                                           Tuyệt ghê        0
81                                         Chị Pu đỉnh        0
82                                Thiik mỗi trọng hiếu        0
83             Trong Hiếu vẫn là 1 cái gì đó out trình        0
84     battle gì mà lắc mông không vậy ạ :')))) sợ quá        0
85                              Như xem hài Chi Pu :))        0
86   Trong hieu la chuyen nghiem roi ko con gi phai...        0
87   bảo ảnh vào làm trò hề àchưa có cái tuổi trong...        0
88                                          DANCE GOOG        0
89   Chi Pu ke đầu nửa vời thì khen lấy khen để. Rồ...        0
90   Kay trần nhảy oke mà mn ơi so vs dân nhảy cx l...        0
91   Con đuông dừa bảo anh và con loăng quăng thị c...        0
92                             Nhìn em bảo anh nhảy vl        0
93           Ke đầu lịch sử=)))) Trò cười thì đúng hơn        0
94               Nhớ cái hồi bước nhảy xì ten ghê  :))        0
95          10p50s cho ai tìm Chipu bẻ cái đầu nhaaaaa        0
96                                    Bảo Anh nhảy🤣🤣🤣🤣        0
97   Nuoc nào cũng vậy thoi đội  trưởng tất nhiên p...        0
98   Ke đâu ke đâu ke đâu ke đâu 🙄🙄, thấy bóng dáng...        0
99   Thà để chi pâu nó nhẩy đi. Đừng để nó cất giọn...        0
100                          Bảo Anh hơi đuối nhở :)))        0
101   Thấy cùi cùi kiểu gì ấy, bên china nhảy đỉnh hơn        0
102  Bảo Anh nhảy chán v~, ra uốn éo vài cái rồi th...        0
103        Nhảy không giỏi mà biểu cảm nó ố dề thật sự        0
104  Mọi người thử search: "Hội những người thất tì...        0
105              nhẩy bòi gì cứ như loăng quăng kk        0
106  Trừ trọng hiếu ra, còn lại thấy nhảy như thời ...        0
107           Treepoo cố hét hay nói to nghe diva vlll        0
108  Nó như kiểu hàng fake của phiên bản Trung Quốc...        0
109  Pha cầm giày của Kay giống của Nhất Bác quá vậ...        0
110  Tao thề là bà bảo anh làm gì trong truong trìn...        0
111             Vào đây để xem quả ke đầu yoga. Duyệt!        0
112                         như đười ươi đu cột điện 💀        2
113  Chipu tấu hài còn cứ hơn bảo anh 1 màu quoá, b...        0
114         T mới đọc báo nên vô coi chi pu ke đầu kkk        0
115           Này gọi là ke à đầu à :)) nhám nhí thiệt        0
116                            xem chọi gà còn vui hơn        0
117  Cho hỏi bà bảo anh nhảy chưa vậy 😑😑.ra nhúng n...        0
118                       8:03 là bài gì vậy mọi người        0
119                   nhảy nhót nhìn chán k chịu được!        0
120                         = ))))))))))))))))))))))))        0
121                  Không bằng mấy e cấp 3 dàn dựng 😂        0
122       Khán giả đc trả bao tiền cho quả ke đầu này?        0
123          má, gì mà như rạp xiếc tấu hài vậy tr :((        0
124  Tôi đang xem cái gì đây :)))) cười k nhặt được...        0
125            Haiz vãi:)) cơ mà Trthanh dct rất duyên        0
126                  xem china xong xem vnam chan cmnl        1
127                    Ban giám khảo còn thua cả dance        0
128  Ô sao có logo giống báo đen của Vương Nhất Bác...        0
129                Pu giờ có vòng eo ngon đấy nhựttt..        0
130           ukm ke đầu lịch sử.. @_@ lịch sử tấu hài        0
131                                   buồn cười vcl :)        1
132                      thách thức danh hài à ace :))        0
133     tôi thấy nó cứ cùi cùi kiểu gì ấy, cả cái show        0
134                            7:03 :> túy quyền đây ư        0
135                     bảo anh làm cái trò mèo gì vậy        0
136           pu oj nho qua thom mjeng nha me may hjjj        0
137     Con Chi Pu nó làm cái gì vạy, nhìn ngứa cả mắt        0
138              Một dislike dành cho CHI PU & BẢO ANH        0
139          Đó gọi là ke hả hay búng lên cái r rớt???        0
140                              Phút 10:49 cho ai cần        0
141  Chương trình thế giới động vật nay mở nhạc to thế        0
142                                             CHÊ :)        0
143                          Bảo Anh nhảy gì vậy? Gớm😅        0
144                                             hahaha        0
145  Kay Trần nhảy cái điệu nhảy cầm giày thấy nó q...        0
146                        Ủa rồi Bảo Anh nhảy chưa? 🤣        0
147                    Trấn Thành có cái áo xấu vãiiii        0
148                     Nhảy cóc nhảy nhái zì vậy?????        0
149                                10:51 react lố vchg        0
150    Éo hiểu con pu nhảy có gì hay mà la hết thế nhỉ        0
151                         Con nít cũng làm dc cái đó        0
152                  Đ khác j mấy con loăng quoăng :))        1
153                            đùa = ))))))) bcuoi vcd        0
154  má ơi thấy bả đăng cái gì ke đầu đỉnh dữ lắm g...        0
155  Thôi cho bà chipu và bà bảo anh về đi hát đi.c...        0
156                      Xếp theo level thìHiếuKayPuBA        0
157                                             Cười ẻ        0
158      Hôm nay xem youtube thế này là đủ r, ngại quá        0
159                                 Game show rác :)))        0
160                                 CRINGE VAIZ CẢ LOZ        0
161                                      Nhảy thấy gớm        0
162                            Clm nói không cũng oét…        1
163  Chi nhảy cx đẹp mà mnMn đánh giá công tâm chút...        0
164  Con kênh 13+1 kêu CP ke đầu đi vào lsu ct làm ...        0
165                    Chương trình tấu hài. Nhảm vccc        0
166                              Hẳn ke đầu 2 giây 🤣🤣🤣        0
167                                     buồn cuoiyvqix        0
168                   Mấy ng này đng làm cái gì dẫy???        1
169                                    kiểu bu vô xu!?        0
170                                  BA nhảy clg v huh        0
171                         Tôi đang xem cái gì v:))??        0
172                      Rạp xiếc trung ương xuất hiện        0
173                                Rạp xiếc trung ương        0
174                                                ???        0
175                                  Tao đang coi clgv        0
176      t chỉ muốn biết là t đang xem cl gì thế này??        1
177                       Clmn làm vô coi ke đầu !!!!!        0